### ISSUE TITLE
Komentarze Marty

### ISSUE THREAD

**Issue by szuvarska** [PrzeChoj/PierwszakNieZoltodziob#5]
### Ad “Nie można powtórzyć modułu i nie można później pójść na niższy.”
https://github.com/PrzeChoj/PierwszakNieZoltodziob/blob/49592707fdd953dd38c316557b4d0fac41bb9113/README.md?plain=1#L136
Dosłownie tak zrobiłam, więc się da, tylko prowadzący/a zajęć musi się zgodzić. W moim przypadku był to francuski prowadzony przez pana Piotra Czarneckiego. Najpierw poszłam na M7, a później na M6.

### Ad “jak coś to piszcie do Marty - powiedziała, że pomoże”
https://github.com/PrzeChoj/PierwszakNieZoltodziob/blob/49592707fdd953dd38c316557b4d0fac41bb9113/README.md?plain=1#L141
Dla studentów -> Rejestracja -> Rejestracje na przedmioty -> [odpowiednia rejestracja]

### Ad “Np. na IiAD na 5 semie jest blok "Programowanie aplikacji wielowarstwowych" i w ramach niego są 2 przedmioty do wyboru.”
https://github.com/PrzeChoj/PierwszakNieZoltodziob/blob/49592707fdd953dd38c316557b4d0fac41bb9113/README.md?plain=1#L308
Akurat mieliśmy tylko jeden XD

### Ad “Za moich czasów WF zaczynał się o pełnych godzinach”
https://github.com/PrzeChoj/PierwszakNieZoltodziob/blob/49592707fdd953dd38c316557b4d0fac41bb9113/README.md?plain=1#L354
Dalej tak jest. Ewentualnie jeszcze :30 po.

### Ad “i chyba ostatnio wykładami z fizyki?”
https://github.com/PrzeChoj/PierwszakNieZoltodziob/blob/49592707fdd953dd38c316557b4d0fac41bb9113/README.md?plain=1#L375
Nieprawda. Natomiast laby z sieci komputerowych są na EiTI.

### Ad “Grammarly - Premium dla studentów. Nie pamiętam jak załatwić”
https://github.com/PrzeChoj/PierwszakNieZoltodziob/blob/49592707fdd953dd38c316557b4d0fac41bb9113/README.md?plain=1#L447
Jest opisane [tutaj](https://bg.pw.edu.pl/index.php/aktualnosci-pl/871-program-grammarly-wersja-premium). Trzeba tylko wypełnić formularz. Tam gdzieś było napisane, że było ważne do kwietnia 2023 tylko, ale mi załatwili w czerwcu i tak.

### Ad “nigdy nie pytajcie się prowadzącego, co może być na egzaminie, bo to bardzo niemiłe”
https://github.com/PrzeChoj/PierwszakNieZoltodziob/blob/49592707fdd953dd38c316557b4d0fac41bb9113/README.md?plain=1#L511
Może niemiłe, nie wiem, ale zdarza się, że po zapytaniu faktycznie dostanie się odpowiedź, która pomoże zawęzić zakres materiału do nauki.

### Ad “Dla chętnych!!! Ja nie wiem czemu oni twierdzą na tej stronie, że jest on obowiązkowy 🙄”
https://github.com/PrzeChoj/PierwszakNieZoltodziob/blob/49592707fdd953dd38c316557b4d0fac41bb9113/README.md?plain=1#L570
W mailu na początku studiów też było napisane, że obowiązkowy: “Praca z Mat-Fiz Samouczkiem jest obowiązkowa, a osiągnięte przez Ciebie wyniki przekazane zostaną Twoim wykładowcom prowadzącym zajęcia z matematyki i z fizyki”. Natomiast nie słyszałam, żeby ktoś nie zdał studiów z powodu niezdania tego. 

### Ad “Nie podciągali, jak ktoś miał zrobiony samouczek, ani nie karali jak ktoś nie miał.”
https://github.com/PrzeChoj/PierwszakNieZoltodziob/blob/49592707fdd953dd38c316557b4d0fac41bb9113/README.md?plain=1#L572
Z analizy matematycznej 1 Dembińska mówiła, że podciągnie z 2 do 3, jeśli komuś brakowało 1 punkta (może 2 też, nie pamiętam), a miał 5 z samouczka.

**Comment by PrzeChoj** [comment]
Uwzględnione w 5c8a0b9.

Dzięki za Komentarze oraz korektę 🤗
